//ALL action types will be exported here.

export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED';
export const INCREMENT = 'INCREMENT';
export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED';
export const DECREMENT = 'DECREMENT';

export const ACTION_CALL = 'ACTION_CALL';
export const CALL_RECIEVED = 'CALL_RECIEVED';
export const CALL_FAILED = 'CALL_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
